INSERT INTO laboratories (id, name, country)
VALUES (gen_random_uuid(), 'ALCOS', 'Bolivia'),
       (gen_random_uuid(), 'ALMAGRAM', 'Bolivia'),
       (gen_random_uuid(), 'ALMOS S.A.', 'Bolivia'),
       (gen_random_uuid(), 'BAGO', 'Argentina'),
       (gen_random_uuid(), 'CHILE', 'Chile'),
       (gen_random_uuid(), 'CHINOIN', 'Mexico'),
       (gen_random_uuid(), 'COFAR', 'Bolivia'),
       (gen_random_uuid(), 'CRESPAL', 'Bolivia'),
       (gen_random_uuid(), 'DELTA', 'Bolivia'),
       (gen_random_uuid(), 'GADOR', 'Argentina'),
       (gen_random_uuid(), 'HAHNEMANN', 'Bolivia'),
       (gen_random_uuid(), 'IFA', 'Bolivia'),
       (gen_random_uuid(), 'IFARBO', 'Bolivia'),
       (gen_random_uuid(), 'INDUFAR', 'Paraguay'),
       (gen_random_uuid(), 'INQUIBOL', 'Bolivia'),
       (gen_random_uuid(), 'INTI', 'Bolivia'),
       (gen_random_uuid(), 'LAFAR', 'Bolivia'),
       (gen_random_uuid(), 'LAQFAGAL', 'Bolivia'),
       (gen_random_uuid(), 'LCFARMA SRL', 'Bolivia'),
       (gen_random_uuid(), 'LHUMAT', 'Bolivia'),
       (gen_random_uuid(), 'LIOMONT', 'Mexico'),
       (gen_random_uuid(), 'LUZA', 'Bolivia'),
       (gen_random_uuid(), 'MEGALABS', 'Uruguay'),
       (gen_random_uuid(), 'MONTPELLIER', 'Argentina'),
       (gen_random_uuid(), 'NOVOPHARMA', 'Bolivia'),
       (gen_random_uuid(), 'PROCAPS', 'Colombia'),
       (gen_random_uuid(), 'QUIMIZA', 'Bolivia'),
       (gen_random_uuid(), 'QUINFA', 'Paraguay'),
       (gen_random_uuid(), 'ROSARIO', 'Bolivia'),
       (gen_random_uuid(), 'SAE', 'Bolivia'),
       (gen_random_uuid(), 'SANAT', 'Bolivia'),
       (gen_random_uuid(), 'SAVAL', 'Chile'),
       (gen_random_uuid(), 'SAVANT', 'Argentina'),
       (gen_random_uuid(), 'SIGMA', 'Bolivia'),
       (gen_random_uuid(), 'TERBOL', 'Bolivia'),
       (gen_random_uuid(), 'VITA', 'Bolivia');